version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  # Mount entire project directory
      - /cloudsql:/cloudsql
    working_dir: /app  # Set working directory
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      cloudsql-proxy:
        condition: service_healthy

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    env_file:
      - .env
    command: >
      /cloud-sql-proxy
      --credentials-file /credentials/cloudsql-credentials.json
      ${CLOUD_SQL_CONNECTION_NAME}
    volumes:
      - ./credentials:/credentials
      - /cloudsql:/cloudsql
    healthcheck:
      test: ["CMD", "/cloud-sql-proxy", "--version"]
      interval: 10s
      timeout: 5s
      retries: 5
