version: '3.3'

services:
  app:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    depends_on:
      cloudsql-proxy:
        condition: service_healthy

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    environment:
      - USE_IAM_AUTH=true
    command: 
      - "--address=0.0.0.0"
      - "--port=5432"
      - "${CLOUD_SQL_CONNECTION_NAME}"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
