version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app  # Only needed for development
      - /cloudsql:/cloudsql  # Critical for Cloud SQL connection
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    env_file:
      - .env
    command: >
      /cloud_sql_proxy
      -instances=${CLOUD_SQL_CONNECTION_NAME}=tcp:5432
      -credential_file=/credentials/cloudsql-credentials.json
    volumes:
      - /cloudsql:/cloudsql
      - ./credentials:/credentials  # Directory containing your service account JSON
    restart: unless-stopped
