version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      cloudsql-proxy:
        condition: service_healthy

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    environment:
      CLOUD_SQL_CONNECTION_NAME: ${CLOUD_SQL_CONNECTION_NAME}
    command: >
      /cloud-sql-proxy
      ${CLOUD_SQL_CONNECTION_NAME}
      --credentials-file /var/run/secrets/cloud.google.com/service-account.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/var/run/secrets/cloud.google.com/service-account.json
    healthcheck:
      test: ["CMD", "/cloud-sql-proxy", "--version"]
      interval: 10s
      timeout: 5s
      retries: 5
